### ISSUE TITLE
Flags missing in the result from ResolveHost

### ISSUE THREAD

**Issue by griff** [stbuehler/rust-async-dnssd#13]
I was playing around the with API making small examples and a major deficiency is that flags `MORE_COMMING` and `ADD`  are missing from both `ScopedSocketAddr` and `ResolveResult`. This means that when the streams that return these structs has a new value you have no way of knowing if that value was added or removed. And you will get two items returned from the stream (one for add and one for removal). I know this because I tested it and can provide you with the code that shows this on request.

Also why are there two flag structs `QueriedRecordFlags` and `BrowsedFlags` that look to represent the exact same values?

**Comment by stbuehler** [comment]
Hi!

Thanks for the input.

Just some initial thoughts:

- [`ResolveResult`](https://stbuehler.github.io/rustdocs/async-dnssd/async_dnssd/struct.ResolveResult.html) comes from [`DNSServiceResolveReply`](https://developer.apple.com/documentation/dnssd/dnsserviceresolvereply), which only lists `MORE_COMING` as possible flag (not `ADD`).
- [`ScopedSocketAddr`](https://stbuehler.github.io/rustdocs/async-dnssd/async_dnssd/enum.ScopedSocketAddr.html) is the streamed item from the helper function [`resolve_host_extended`](https://stbuehler.github.io/rustdocs/async-dnssd/async_dnssd/fn.resolve_host_extended.html), which internally queries both `A` and `AAAA`. It should forward the `ADD` flag, but `MORE_COMING` has unclear semantics (as there are two underlying streams). I think I'm gonna wrap `ScopedSocketAddr` in a `ResolveHostResult` struct, which then also would contain the flags.
- I used per "function" `*Flags`, so that I can more easily add new flags to a usecase, and the name of the flags type should indicate what function it belongs to.

I probably should make various types `#[non_exhaustive]` too.

**Comment by stbuehler** [comment]
non-exhaustive parts also done.
